### ISSUE TITLE
no output

### ISSUE THREAD

**Issue by occdi** [cr0sd/freqr#1]
Hi, I run this 
./freqr -f 440 -w sn
but the raw.dat file is empty

**Comment by pvtroswold** [comment]
What does the log file say for you?

**Comment by pvtroswold** [comment]
Judging by your "./" syntax I'm assuming you're using Unix, which I am unable to test on unfortunately (it does work on Windows for me). I will try to investigate this further. Thank you.

**Comment by cr0sd** [comment]
.....Suddenly I find myself with Ubuntu Linux and have tested it. It does indeed work for me. Try this:
`cc freqr.c -o freqr -lm`
`./freqr -f 440`
`sox -b 16 -c 1 -r 44100 -e signed-integer -t raw raw.dat -t wav raw.wav`
`play raw.wav`
